/**
 * A curated set, not a full emoji database — picked for what actually shows
 * up in docs sidebars (status, sections, tech, people/roles) rather than
 * bundling every emoji that exists. Each entry's `keywords` is what the
 * picker's search matches against, in addition to its own name.
 */
export interface PageIconEntry {
  emoji: string;
  name: string;
  keywords: string[];
}

export const PAGE_ICONS: PageIconEntry[] = [
  { emoji: "📄", name: "page", keywords: ["document", "file"] },
  { emoji: "📝", name: "notes", keywords: ["write", "edit", "memo"] },
  { emoji: "📚", name: "books", keywords: ["docs", "library", "reference"] },
  { emoji: "📖", name: "open book", keywords: ["docs", "guide", "read"] },
  { emoji: "🚀", name: "rocket", keywords: ["launch", "start", "quickstart", "getting started"] },
  { emoji: "🏁", name: "checkered flag", keywords: ["start", "finish", "goal"] },
  { emoji: "🧭", name: "compass", keywords: ["navigate", "guide", "overview"] },
  { emoji: "🗺️", name: "map", keywords: ["overview", "roadmap"] },
  { emoji: "✅", name: "check mark", keywords: ["done", "complete", "yes", "success"] },
  { emoji: "☑️", name: "checkbox", keywords: ["task", "todo"] },
  { emoji: "⚠️", name: "warning", keywords: ["caution", "alert", "danger"] },
  { emoji: "🚫", name: "prohibited", keywords: ["no", "forbidden", "stop"] },
  { emoji: "🛑", name: "stop sign", keywords: ["stop", "halt", "critical"] },
  { emoji: "🔥", name: "fire", keywords: ["hot", "urgent", "trending"] },
  { emoji: "💡", name: "light bulb", keywords: ["idea", "tip", "hint"] },
  { emoji: "❓", name: "question mark", keywords: ["faq", "help", "question"] },
  { emoji: "❗", name: "exclamation", keywords: ["important", "notice"] },
  { emoji: "🔒", name: "locked", keywords: ["security", "private", "auth"] },
  { emoji: "🔓", name: "unlocked", keywords: ["public", "open", "access"] },
  { emoji: "🔑", name: "key", keywords: ["auth", "access", "api key", "login"] },
  { emoji: "🛡️", name: "shield", keywords: ["security", "protection", "moderation"] },
  { emoji: "⚙️", name: "gear", keywords: ["settings", "config", "configuration"] },
  { emoji: "🔧", name: "wrench", keywords: ["tools", "fix", "config"] },
  { emoji: "🛠️", name: "tools", keywords: ["build", "setup", "maintenance"] },
  { emoji: "🧩", name: "puzzle piece", keywords: ["integration", "plugin", "extension"] },
  { emoji: "📦", name: "package", keywords: ["install", "release", "module"] },
  { emoji: "🏗️", name: "construction", keywords: ["wip", "building", "in progress"] },
  { emoji: "🧪", name: "test tube", keywords: ["test", "testing", "experiment", "beta"] },
  { emoji: "🐛", name: "bug", keywords: ["bug", "debug", "issue"] },
  { emoji: "💻", name: "laptop", keywords: ["code", "dev", "development"] },
  { emoji: "⌨️", name: "keyboard", keywords: ["shortcuts", "hotkeys", "input"] },
  { emoji: "🖥️", name: "desktop", keywords: ["app", "software", "system"] },
  { emoji: "📱", name: "mobile phone", keywords: ["mobile", "app", "device"] },
  { emoji: "🌐", name: "globe", keywords: ["web", "network", "internet", "domain"] },
  { emoji: "🔗", name: "link", keywords: ["url", "hyperlink", "reference"] },
  { emoji: "📡", name: "satellite", keywords: ["api", "webhook", "network"] },
  { emoji: "🗄️", name: "file cabinet", keywords: ["database", "storage", "archive"] },
  { emoji: "💾", name: "floppy disk", keywords: ["save", "storage", "backup"] },
  { emoji: "📊", name: "bar chart", keywords: ["analytics", "stats", "data"] },
  { emoji: "📈", name: "chart increasing", keywords: ["growth", "analytics", "metrics"] },
  { emoji: "🧮", name: "abacus", keywords: ["math", "calculation", "billing"] },
  { emoji: "💰", name: "money bag", keywords: ["billing", "payment", "pricing", "economy"] },
  { emoji: "💳", name: "credit card", keywords: ["payment", "billing"] },
  { emoji: "🛒", name: "shopping cart", keywords: ["store", "shop", "purchase"] },
  { emoji: "🎁", name: "gift", keywords: ["reward", "bonus", "crate"] },
  { emoji: "🏆", name: "trophy", keywords: ["rank", "achievement", "leaderboard"] },
  { emoji: "⭐", name: "star", keywords: ["favorite", "rating", "featured"] },
  { emoji: "🎯", name: "target", keywords: ["goal", "focus"] },
  { emoji: "👤", name: "person", keywords: ["user", "account", "profile"] },
  { emoji: "👥", name: "people", keywords: ["users", "team", "members"] },
  { emoji: "🧑‍💼", name: "staff", keywords: ["admin", "staff", "team", "employee"] },
  { emoji: "🛎️", name: "bell", keywords: ["support", "ticket", "notification"] },
  { emoji: "💬", name: "speech bubble", keywords: ["chat", "comment", "discord", "support"] },
  { emoji: "📣", name: "megaphone", keywords: ["announcement", "broadcast"] },
  { emoji: "📮", name: "mailbox", keywords: ["contact", "email", "feedback"] },
  { emoji: "📧", name: "email", keywords: ["mail", "contact"] },
  { emoji: "🔍", name: "magnifying glass", keywords: ["search", "find", "lookup"] },
  { emoji: "🕵️", name: "detective", keywords: ["moderation", "anti-cheat", "investigation"] },
  { emoji: "🚨", name: "police light", keywords: ["alert", "moderation", "emergency"] },
  { emoji: "⚖️", name: "balance scale", keywords: ["rules", "policy", "punishment", "law"] },
  { emoji: "🔨", name: "hammer", keywords: ["ban", "punishment", "moderation"] },
  { emoji: "🧱", name: "brick", keywords: ["build", "block", "grief"] },
  { emoji: "🌍", name: "earth", keywords: ["world", "server", "global"] },
  { emoji: "🖼️", name: "framed picture", keywords: ["image", "media", "gallery"] },
  { emoji: "🎨", name: "palette", keywords: ["design", "theme", "style", "branding"] },
  { emoji: "🧵", name: "thread", keywords: ["variables", "reusable"] },
  { emoji: "🔀", name: "shuffle", keywords: ["variants", "redirect", "routing"] },
  { emoji: "🕒", name: "clock", keywords: ["history", "time", "schedule", "changelog"] },
  { emoji: "🆕", name: "new", keywords: ["new", "update", "changelog"] },
  { emoji: "📅", name: "calendar", keywords: ["date", "schedule", "changelog"] },
];
