import {
  AirplaneIcon,
  AlarmIcon,
  ArrowSquareOutIcon,
  ArrowsClockwiseIcon,
  ArticleIcon,
  BellIcon,
  BookIcon,
  BookOpenIcon,
  BroadcastIcon,
  BugIcon,
  BuildingsIcon,
  CalculatorIcon,
  CalendarBlankIcon,
  CalendarCheckIcon,
  CertificateIcon,
  ChartBarIcon,
  ChartDonutIcon,
  ChartLineIcon,
  ChartPieSliceIcon,
  ChatCircleIcon,
  CheckCircleIcon,
  CheckSquareIcon,
  ClipboardTextIcon,
  ClockCounterClockwiseIcon,
  ClockIcon,
  CloudCheckIcon,
  CloudIcon,
  CodeIcon,
  CoinsIcon,
  CompassIcon,
  ConfettiIcon,
  CpuIcon,
  CreditCardIcon,
  CrownIcon,
  CubeIcon,
  DatabaseIcon,
  DesktopIcon,
  DetectiveIcon,
  DeviceMobileIcon,
  DiamondIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FadersIcon,
  FileIcon,
  FilePlusIcon,
  FileTextIcon,
  FilesIcon,
  FingerprintIcon,
  FireIcon,
  FlagCheckeredIcon,
  FlagIcon,
  FloppyDiskIcon,
  FolderIcon,
  FolderOpenIcon,
  GearSixIcon,
  GitBranchIcon,
  GithubLogoIcon,
  GiftIcon,
  GlobeIcon,
  GraduationCapIcon,
  HammerIcon,
  HandWavingIcon,
  HandshakeIcon,
  HardDrivesIcon,
  HardHatIcon,
  HeartIcon,
  HourglassIcon,
  HouseIcon,
  ImageIcon,
  ImagesIcon,
  InfoIcon,
  KanbanIcon,
  KeyIcon,
  KeyboardIcon,
  LaptopIcon,
  LayoutIcon,
  LeafIcon,
  LightbulbIcon,
  LightningIcon,
  LinkIcon,
  ListBulletsIcon,
  ListChecksIcon,
  LockKeyIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapTrifoldIcon,
  MedalIcon,
  MegaphoneIcon,
  MonitorPlayIcon,
  MoneyIcon,
  NewspaperIcon,
  NotebookIcon,
  NotePencilIcon,
  PackageIcon,
  PaintBrushIcon,
  PaletteIcon,
  PathIcon,
  PencilSimpleIcon,
  PlayIcon,
  PlugIcon,
  PlugsIcon,
  PresentationIcon,
  ProhibitIcon,
  PuzzlePieceIcon,
  QuestionIcon,
  ReceiptIcon,
  RecycleIcon,
  RocketIcon,
  ScalesIcon,
  ScrewdriverIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShieldStarIcon,
  ShieldWarningIcon,
  ShoppingCartIcon,
  SignpostIcon,
  SirenIcon,
  SlidersHorizontalIcon,
  SparkleIcon,
  SquaresFourIcon,
  StackIcon,
  StarIcon,
  StorefrontIcon,
  TableIcon,
  TagIcon,
  TargetIcon,
  TerminalIcon,
  TestTubeIcon,
  ThumbsUpIcon,
  TimerIcon,
  ToggleLeftIcon,
  ToolboxIcon,
  TrophyIcon,
  UploadSimpleIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  WalletIcon,
  WarningCircleIcon,
  WarningIcon,
  WarningOctagonIcon,
  WifiHighIcon,
  WrenchIcon,
  type Icon,
} from "@phosphor-icons/react";

/**
 * A curated set of Phosphor's icons (a single consistent flat/outline family,
 * not emoji — emoji render inconsistently across platforms and clash with a
 * docs site's own visual language). `slug` is what's actually stored on
 * Page.icon; the component is looked up from it at render time (see
 * PageIcon.tsx), never stored directly, so this list can be reordered or
 * extended without touching any saved data. `keywords` only needs to cover
 * search terms *beyond* the icon's own name/slug — the picker already
 * matches those directly.
 */
export interface PageIconEntry {
  slug: string;
  label: string;
  Icon: Icon;
  keywords: string[];
}

export const PAGE_ICONS: PageIconEntry[] = [
  { slug: "file", label: "File", Icon: FileIcon, keywords: ["document", "page"] },
  { slug: "file-text", label: "File text", Icon: FileTextIcon, keywords: ["document", "notes"] },
  { slug: "file-plus", label: "New file", Icon: FilePlusIcon, keywords: ["add", "create"] },
  { slug: "files", label: "Files", Icon: FilesIcon, keywords: ["documents", "copy"] },
  { slug: "note-pencil", label: "Notes", Icon: NotePencilIcon, keywords: ["write", "edit", "memo"] },
  { slug: "notebook", label: "Notebook", Icon: NotebookIcon, keywords: ["journal", "log"] },
  { slug: "clipboard-text", label: "Clipboard", Icon: ClipboardTextIcon, keywords: ["checklist", "form"] },
  { slug: "book", label: "Book", Icon: BookIcon, keywords: ["docs", "library", "reference"] },
  { slug: "book-open", label: "Open book", Icon: BookOpenIcon, keywords: ["docs", "guide", "read"] },
  { slug: "graduation-cap", label: "Graduation cap", Icon: GraduationCapIcon, keywords: ["learn", "tutorial", "education"] },
  { slug: "article", label: "Article", Icon: ArticleIcon, keywords: ["blog", "post"] },
  { slug: "newspaper", label: "Newspaper", Icon: NewspaperIcon, keywords: ["news", "updates", "press"] },
  { slug: "certificate", label: "Certificate", Icon: CertificateIcon, keywords: ["award", "credential", "license"] },

  { slug: "rocket", label: "Rocket", Icon: RocketIcon, keywords: ["launch", "start", "quickstart", "getting started"] },
  { slug: "flag-checkered", label: "Checkered flag", Icon: FlagCheckeredIcon, keywords: ["start", "finish", "goal"] },
  { slug: "flag", label: "Flag", Icon: FlagIcon, keywords: ["milestone", "report", "mark"] },
  { slug: "compass", label: "Compass", Icon: CompassIcon, keywords: ["navigate", "guide", "overview"] },
  { slug: "map-trifold", label: "Map", Icon: MapTrifoldIcon, keywords: ["overview", "roadmap"] },
  { slug: "map-pin", label: "Map pin", Icon: MapPinIcon, keywords: ["location", "place"] },
  { slug: "signpost", label: "Signpost", Icon: SignpostIcon, keywords: ["direction", "routing"] },
  { slug: "path", label: "Path", Icon: PathIcon, keywords: ["flow", "route", "journey"] },
  { slug: "target", label: "Target", Icon: TargetIcon, keywords: ["goal", "focus"] },

  { slug: "check-circle", label: "Check circle", Icon: CheckCircleIcon, keywords: ["done", "complete", "success"] },
  { slug: "check-square", label: "Checkbox", Icon: CheckSquareIcon, keywords: ["task", "todo"] },
  { slug: "list-checks", label: "Checklist", Icon: ListChecksIcon, keywords: ["todo", "steps", "tasks"] },
  { slug: "warning", label: "Warning", Icon: WarningIcon, keywords: ["caution", "alert"] },
  { slug: "warning-circle", label: "Warning circle", Icon: WarningCircleIcon, keywords: ["caution", "alert", "notice"] },
  { slug: "warning-octagon", label: "Stop warning", Icon: WarningOctagonIcon, keywords: ["danger", "critical", "halt"] },
  { slug: "prohibit", label: "Prohibited", Icon: ProhibitIcon, keywords: ["no", "forbidden", "stop", "banned"] },
  { slug: "fire", label: "Fire", Icon: FireIcon, keywords: ["hot", "urgent", "trending"] },
  { slug: "lightbulb", label: "Light bulb", Icon: LightbulbIcon, keywords: ["idea", "tip", "hint"] },
  { slug: "sparkle", label: "Sparkle", Icon: SparkleIcon, keywords: ["new", "feature", "highlight"] },
  { slug: "lightning", label: "Lightning", Icon: LightningIcon, keywords: ["fast", "power", "performance"] },
  { slug: "question", label: "Question mark", Icon: QuestionIcon, keywords: ["faq", "help"] },
  { slug: "info", label: "Info", Icon: InfoIcon, keywords: ["note", "about"] },

  { slug: "lock-key", label: "Locked", Icon: LockKeyIcon, keywords: ["security", "private", "auth"] },
  { slug: "lock-open", label: "Unlocked", Icon: LockOpenIcon, keywords: ["public", "open", "access"] },
  { slug: "key", label: "Key", Icon: KeyIcon, keywords: ["auth", "access", "api key", "login"] },
  { slug: "fingerprint", label: "Fingerprint", Icon: FingerprintIcon, keywords: ["identity", "biometric", "auth"] },
  { slug: "shield", label: "Shield", Icon: ShieldIcon, keywords: ["security", "protection"] },
  { slug: "shield-check", label: "Shield check", Icon: ShieldCheckIcon, keywords: ["verified", "protected", "safe"] },
  { slug: "shield-warning", label: "Shield warning", Icon: ShieldWarningIcon, keywords: ["risk", "moderation"] },
  { slug: "shield-star", label: "Shield star", Icon: ShieldStarIcon, keywords: ["premium", "trusted"] },
  { slug: "seal-check", label: "Verified seal", Icon: SealCheckIcon, keywords: ["verified", "approved", "official"] },
  { slug: "eye", label: "Eye", Icon: EyeIcon, keywords: ["view", "visible", "preview"] },
  { slug: "eye-slash", label: "Eye slash", Icon: EyeSlashIcon, keywords: ["hidden", "private"] },

  { slug: "gear-six", label: "Gear", Icon: GearSixIcon, keywords: ["settings", "config", "configuration"] },
  { slug: "sliders-horizontal", label: "Sliders", Icon: SlidersHorizontalIcon, keywords: ["settings", "adjust", "filters"] },
  { slug: "faders", label: "Faders", Icon: FadersIcon, keywords: ["settings", "tune", "filters"] },
  { slug: "toggle-left", label: "Toggle", Icon: ToggleLeftIcon, keywords: ["switch", "flag", "feature flag"] },
  { slug: "wrench", label: "Wrench", Icon: WrenchIcon, keywords: ["tools", "fix", "config"] },
  { slug: "toolbox", label: "Toolbox", Icon: ToolboxIcon, keywords: ["build", "setup", "maintenance"] },
  { slug: "screwdriver", label: "Screwdriver", Icon: ScrewdriverIcon, keywords: ["tools", "repair", "build"] },
  { slug: "hard-hat", label: "Hard hat", Icon: HardHatIcon, keywords: ["construction", "wip", "building"] },
  { slug: "puzzle-piece", label: "Puzzle piece", Icon: PuzzlePieceIcon, keywords: ["integration", "plugin", "extension"] },
  { slug: "package", label: "Package", Icon: PackageIcon, keywords: ["install", "release", "module"] },
  { slug: "test-tube", label: "Test tube", Icon: TestTubeIcon, keywords: ["test", "testing", "experiment", "beta"] },
  { slug: "bug", label: "Bug", Icon: BugIcon, keywords: ["debug", "issue"] },

  { slug: "code", label: "Code", Icon: CodeIcon, keywords: ["dev", "development", "snippet"] },
  { slug: "terminal", label: "Terminal", Icon: TerminalIcon, keywords: ["console", "cli", "shell"] },
  { slug: "laptop", label: "Laptop", Icon: LaptopIcon, keywords: ["dev", "computer"] },
  { slug: "desktop", label: "Desktop", Icon: DesktopIcon, keywords: ["app", "software", "system"] },
  { slug: "device-mobile", label: "Mobile phone", Icon: DeviceMobileIcon, keywords: ["mobile", "app", "device"] },
  { slug: "keyboard", label: "Keyboard", Icon: KeyboardIcon, keywords: ["shortcuts", "hotkeys", "input"] },
  { slug: "cpu", label: "CPU", Icon: CpuIcon, keywords: ["hardware", "processor", "performance"] },
  { slug: "hard-drives", label: "Hard drives", Icon: HardDrivesIcon, keywords: ["storage", "disk"] },
  { slug: "git-branch", label: "Git branch", Icon: GitBranchIcon, keywords: ["git", "version control", "repo"] },
  { slug: "github-logo", label: "GitHub", Icon: GithubLogoIcon, keywords: ["git", "repo", "source"] },

  { slug: "globe", label: "Globe", Icon: GlobeIcon, keywords: ["web", "network", "internet", "domain"] },
  { slug: "link", label: "Link", Icon: LinkIcon, keywords: ["url", "hyperlink", "reference"] },
  { slug: "arrow-square-out", label: "External link", Icon: ArrowSquareOutIcon, keywords: ["outbound", "leave"] },
  { slug: "broadcast", label: "Broadcast", Icon: BroadcastIcon, keywords: ["api", "webhook", "signal"] },
  { slug: "wifi-high", label: "Wifi", Icon: WifiHighIcon, keywords: ["network", "connection", "online"] },
  { slug: "cloud", label: "Cloud", Icon: CloudIcon, keywords: ["hosting", "storage", "infra"] },
  { slug: "cloud-check", label: "Cloud check", Icon: CloudCheckIcon, keywords: ["synced", "backup", "saved"] },
  { slug: "database", label: "Database", Icon: DatabaseIcon, keywords: ["storage", "sql", "data"] },
  { slug: "floppy-disk", label: "Floppy disk", Icon: FloppyDiskIcon, keywords: ["save", "storage", "backup"] },
  { slug: "download-simple", label: "Download", Icon: DownloadSimpleIcon, keywords: ["export", "save"] },
  { slug: "upload-simple", label: "Upload", Icon: UploadSimpleIcon, keywords: ["import", "add"] },

  { slug: "chart-bar", label: "Bar chart", Icon: ChartBarIcon, keywords: ["analytics", "stats", "data"] },
  { slug: "chart-line", label: "Line chart", Icon: ChartLineIcon, keywords: ["growth", "analytics", "metrics", "trend"] },
  { slug: "chart-pie-slice", label: "Pie chart", Icon: ChartPieSliceIcon, keywords: ["analytics", "breakdown", "stats"] },
  { slug: "chart-donut", label: "Donut chart", Icon: ChartDonutIcon, keywords: ["analytics", "breakdown", "stats"] },
  { slug: "kanban", label: "Kanban", Icon: KanbanIcon, keywords: ["board", "workflow", "project"] },
  { slug: "table", label: "Table", Icon: TableIcon, keywords: ["grid", "spreadsheet", "data"] },
  { slug: "list-bullets", label: "List", Icon: ListBulletsIcon, keywords: ["bullets", "outline"] },
  { slug: "layout", label: "Layout", Icon: LayoutIcon, keywords: ["structure", "template"] },
  { slug: "squares-four", label: "Grid", Icon: SquaresFourIcon, keywords: ["apps", "dashboard", "overview"] },
  { slug: "stack", label: "Stack", Icon: StackIcon, keywords: ["layers", "collection"] },
  { slug: "presentation", label: "Presentation", Icon: PresentationIcon, keywords: ["slides", "deck", "demo"] },
  { slug: "calculator", label: "Calculator", Icon: CalculatorIcon, keywords: ["math", "calculation"] },

  { slug: "money", label: "Money", Icon: MoneyIcon, keywords: ["billing", "payment", "pricing"] },
  { slug: "coins", label: "Coins", Icon: CoinsIcon, keywords: ["currency", "economy", "payment"] },
  { slug: "credit-card", label: "Credit card", Icon: CreditCardIcon, keywords: ["payment", "billing"] },
  { slug: "wallet", label: "Wallet", Icon: WalletIcon, keywords: ["payment", "billing", "account"] },
  { slug: "receipt", label: "Receipt", Icon: ReceiptIcon, keywords: ["invoice", "billing", "order"] },
  { slug: "shopping-cart", label: "Shopping cart", Icon: ShoppingCartIcon, keywords: ["store", "shop", "purchase"] },
  { slug: "storefront", label: "Storefront", Icon: StorefrontIcon, keywords: ["shop", "store", "market"] },
  { slug: "gift", label: "Gift", Icon: GiftIcon, keywords: ["reward", "bonus"] },
  { slug: "trophy", label: "Trophy", Icon: TrophyIcon, keywords: ["rank", "achievement", "leaderboard", "winner"] },
  { slug: "medal", label: "Medal", Icon: MedalIcon, keywords: ["award", "achievement", "rank"] },
  { slug: "star", label: "Star", Icon: StarIcon, keywords: ["favorite", "rating", "featured"] },
  { slug: "crown", label: "Crown", Icon: CrownIcon, keywords: ["premium", "vip", "admin", "royal"] },
  { slug: "diamond", label: "Diamond", Icon: DiamondIcon, keywords: ["premium", "rare", "gem"] },

  { slug: "user", label: "Person", Icon: UserIcon, keywords: ["account", "profile"] },
  { slug: "user-circle", label: "User circle", Icon: UserCircleIcon, keywords: ["account", "profile", "avatar"] },
  { slug: "users", label: "People", Icon: UsersIcon, keywords: ["team", "members", "staff"] },
  { slug: "hand-waving", label: "Wave", Icon: HandWavingIcon, keywords: ["hello", "welcome", "greeting"] },
  { slug: "handshake", label: "Handshake", Icon: HandshakeIcon, keywords: ["deal", "partnership", "agreement"] },
  { slug: "heart", label: "Heart", Icon: HeartIcon, keywords: ["like", "favorite", "love"] },
  { slug: "thumbs-up", label: "Thumbs up", Icon: ThumbsUpIcon, keywords: ["like", "approve", "good"] },
  { slug: "confetti", label: "Confetti", Icon: ConfettiIcon, keywords: ["celebration", "party", "launch"] },

  { slug: "bell", label: "Bell", Icon: BellIcon, keywords: ["notification", "alert", "support"] },
  { slug: "chat-circle", label: "Chat", Icon: ChatCircleIcon, keywords: ["comment", "discord", "support", "message"] },
  { slug: "megaphone", label: "Megaphone", Icon: MegaphoneIcon, keywords: ["announcement", "broadcast"] },
  { slug: "envelope", label: "Envelope", Icon: EnvelopeIcon, keywords: ["mail", "email", "contact"] },
  { slug: "envelope-simple", label: "Mail", Icon: EnvelopeSimpleIcon, keywords: ["email", "contact", "feedback"] },
  { slug: "magnifying-glass", label: "Search", Icon: MagnifyingGlassIcon, keywords: ["find", "lookup"] },
  { slug: "detective", label: "Detective", Icon: DetectiveIcon, keywords: ["moderation", "investigation", "anti-cheat"] },
  { slug: "siren", label: "Siren", Icon: SirenIcon, keywords: ["alert", "moderation", "emergency"] },
  { slug: "scales", label: "Scales", Icon: ScalesIcon, keywords: ["rules", "policy", "law", "justice"] },
  { slug: "hammer", label: "Hammer", Icon: HammerIcon, keywords: ["ban", "punishment", "moderation", "build"] },

  { slug: "house", label: "House", Icon: HouseIcon, keywords: ["home", "start"] },
  { slug: "buildings", label: "Buildings", Icon: BuildingsIcon, keywords: ["company", "organization", "office"] },
  { slug: "cube", label: "Cube", Icon: CubeIcon, keywords: ["3d", "block", "object"] },
  { slug: "image", label: "Image", Icon: ImageIcon, keywords: ["media", "photo", "picture"] },
  { slug: "images", label: "Images", Icon: ImagesIcon, keywords: ["gallery", "media", "photos"] },
  { slug: "video", label: "Video", Icon: VideoIcon, keywords: ["media", "clip", "recording"] },
  { slug: "monitor-play", label: "Video player", Icon: MonitorPlayIcon, keywords: ["watch", "stream", "tutorial"] },
  { slug: "play", label: "Play", Icon: PlayIcon, keywords: ["start", "run", "video"] },
  { slug: "paint-brush", label: "Paint brush", Icon: PaintBrushIcon, keywords: ["design", "art"] },
  { slug: "palette", label: "Palette", Icon: PaletteIcon, keywords: ["design", "theme", "style", "branding"] },

  { slug: "arrows-clockwise", label: "Sync", Icon: ArrowsClockwiseIcon, keywords: ["refresh", "update", "reload"] },
  { slug: "clock-counter-clockwise", label: "History", Icon: ClockCounterClockwiseIcon, keywords: ["history", "time", "changelog", "revert"] },
  { slug: "clock", label: "Clock", Icon: ClockIcon, keywords: ["time", "schedule"] },
  { slug: "timer", label: "Timer", Icon: TimerIcon, keywords: ["countdown", "duration"] },
  { slug: "hourglass", label: "Hourglass", Icon: HourglassIcon, keywords: ["waiting", "pending", "loading"] },
  { slug: "alarm", label: "Alarm", Icon: AlarmIcon, keywords: ["reminder", "wake"] },
  { slug: "calendar-blank", label: "Calendar", Icon: CalendarBlankIcon, keywords: ["date", "schedule", "changelog"] },
  { slug: "calendar-check", label: "Calendar check", Icon: CalendarCheckIcon, keywords: ["scheduled", "confirmed", "date"] },

  { slug: "tag", label: "Tag", Icon: TagIcon, keywords: ["label", "category"] },
  { slug: "plug", label: "Plug", Icon: PlugIcon, keywords: ["connect", "integration"] },
  { slug: "plugs", label: "Plugs", Icon: PlugsIcon, keywords: ["disconnect", "integration"] },
  { slug: "airplane", label: "Airplane", Icon: AirplaneIcon, keywords: ["travel", "launch", "flight"] },
  { slug: "leaf", label: "Leaf", Icon: LeafIcon, keywords: ["eco", "nature", "sustainable"] },
  { slug: "recycle", label: "Recycle", Icon: RecycleIcon, keywords: ["reuse", "sustainable", "loop"] },
];

export function findPageIcon(slug: string | null | undefined): PageIconEntry | undefined {
  if (!slug) return undefined;
  return PAGE_ICONS.find((entry) => entry.slug === slug);
}
